
name: Connect to an AWS role from a GitHub repository

# Controls when the action will run. Invokes the workflow on push events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  
  AWS_REGION : us-east-2

# Permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        id: assume_role
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::999173078628:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to Elastic Beanstalk
        run: |
          # Your deployment commands here
          aws elasticbeanstalk create-application-version \
            --application-name quil \
            --version-label $GITHUB_SHA \
          aws elasticbeanstalk update-environment \
            --environment-name quil-prod \
            --version-label $GITHUB_SHA
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          KEY: ${{ secrets.KEY }}
          SALT_WORK_FACTOR: ${{ secrets.SALT_WORK_FACTOR }}
          PORT: ${{ secrets.PORT }}
          REACT_APP_FORM_ENDPOINT: ${{ secrets.REACT_APP_FORM_ENDPOINT }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
     
      # Hello from AWS: WhoAmI
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity
