name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/setup-aws-cli@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to Elastic Beanstalk
      run: |
        aws elasticbeanstalk create-application-version \
          --application-name quil \
          --version-label $GITHUB_SHA \
          --source-bundle S3Bucket=elasticbeanstalk-${{ secrets.AWS_REGION }},S3Key=$GITHUB_SHA.zip
          
        aws elasticbeanstalk update-environment \
          --environment-name quil \
          --version-label $GITHUB_SHA
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        KEY: ${{ secrets.KEY }}
        SALT_WORK_FACTOR: ${{ secrets.SALT_WORK_FACTOR }}
        PORT: ${{ secrets.PORT }}
        REACT_APP_FORM_ENDPOINT: ${{ secrets.REACT_APP_FORM_ENDPOINT }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
